desc 'test lane'
lane :test do
    sh('echo', 'Test... OK!')
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    register_devices(
      devices_file: './devices.txt'
    )
    match(type: 'development', force_for_new_devices: true)
    match(type: "appstore")
  end

  lane :builddev do
    setup_ci()
    match(type: "development", readonly: true)
    ENV['MATCH_PROVISIONING_PROFILE'] ||= ENV['sigh_io.nstudio.test.gh.action_development_profile-name']

    # build nativescript app
    Dir.chdir('..') do
        sh(
            'tns', 'build', 'ios',
            '--for-device',
            '--copy-to', './dist/build.ipa',
            '--release',
            '--env.production',
            '--provision', ENV['MATCH_PROVISIONING_PROFILE'],
            '--log', 'trace'
            # '--env.uglify'
        )
    end
  end

  lane :build do
      setup_ci()
      match(type: "appstore", readonly: true)
      ENV['MATCH_PROVISIONING_PROFILE'] ||= ENV['sigh_io.nstudio.test.gh.action_appstore_profile-name']

      # build nativescript app
      Dir.chdir('..') do
          sh(
              'tns', 'build', 'ios',
              '--for-device',
              '--copy-to', './dist/build.ipa',
              '--release',
              '--env.production',
              '--provision', ENV['MATCH_PROVISIONING_PROFILE'],
              '--log', 'trace'
              # '--env.uglify'
          )
      end
    end

  lane :bump_build_number do
    build_number = latest_testflight_build_number.to_i + 1

    set_info_plist_value(
        path: 'app/App_Resources/iOS/Info.plist',
        key: 'CFBundleVersion',
        value: build_number.to_s
    )
  end

  desc 'Ship to Testflight.'
  lane :beta do
    bump_build_number()

    build()

    upload_to_testflight(
      beta_app_description: "support@nativescript.org",
      beta_app_feedback_email: "support@nativescript.org",
      demo_account_required: false,
      distribute_external: true,
      groups: ["beta testers"],
      ipa: './dist/build.ipa',
      notify_external_testers: false,
      beta_app_review_info: {
        contact_email: "support@nativescript.org",
        contact_first_name: "Native",
        contact_last_name: "Script",
        contact_phone: "(866) 344-9898",
        demo_account_name: "",
        demo_account_password: "",
        notes: "<3 Thank you for reviewing!"
      },
    )
  end
end
