desc 'test lane'
lane :test do
    sh('echo', 'Test... OK!')
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(type: 'development')
    match(type: "appstore")
  end

  lane :build do
    match(type: "appstore", readonly: true)
    ENV['MATCH_PROVISIONING_PROFILE'] ||= ENV['sigh_io.nstudio.test.gh.action_appstore_profile-name']

    # build nativescript app
    sh(
        'cd', '..', '&&',
        'tns', 'build', 'ios',
        # '--for-device',
        '--copy-to', './dist/build.ipa',
        '--release',
        '--env.production',
        '--provision', ENV['MATCH_PROVISIONING_PROFILE'],
        '--log', 'trace'
        # '--env.uglify'
    )
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build

    changelog_from_git_commits

    upload_to_testflight(
      beta_app_description: "support@nativescript.org",
      beta_app_feedback_email: "support@nativescript.org",
      demo_account_required: false,
      distribute_external: true,
      groups: ["beta testers"],
      ipa: './dist/build.ipa',
      notify_external_testers: true,
      beta_app_review_info: {
        contact_email: "support@nativescript.org",
        contact_first_name: "Native",
        contact_last_name: "Script",
        contact_phone: "(866) 344-9898",
        demo_account_name: "",
        demo_account_password: "",
        notes: "<3 Thank you for reviewing!"
      },
    )
  end
end
